# -*- coding: utf-8 -*-
"""SARIMAX Firebase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ED8rDdoRApxaOPA3aGZQ5icIF61tbUeM
"""

!pip install "shimmy>=2.0" stable-baselines3 gym statsmodels requests -q
import os
import time
import pickle
import requests
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import firebase_admin
from firebase_admin import credentials, db
from statsmodels.tsa.statespace.sarimax import SARIMAX
import gym
from gym import spaces
from stable_baselines3 import PPO

from google.colab import drive
drive.mount('/content/drive')

PATH_JSON = '/content/drive/MyDrive/SKRIPSHIT/firebase-project/firebase-project/serviceAccountKey.json'
DB_URL = 'https://test-reading-the-pzem-default-rtdb.asia-southeast1.firebasedatabase.app'

if not firebase_admin._apps:
    cred = credentials.Certificate(PATH_JSON)
    firebase_admin.initialize_app(cred, {'databaseURL': DB_URL})
    print("✅ [Step 1] Firebase Berhasil Terhubung!")
else:
    print("✅ [Step 1] Firebase Sudah Aktif.")

print("⏳ [Step 2] Menarik data History, Log Konfirmasi, dan Cuaca Satelit...")
raw_hist = db.reference('history').get()
raw_logs = db.reference('log_konfirmasi').get()

# Proses Data Sensor
df_pzem = pd.DataFrame.from_dict(raw_hist, orient='index')
waktu_akhir = datetime.now()
df_pzem['timestamp_dt'] = pd.date_range(end=waktu_akhir, periods=len(df_pzem), freq='10s')
df_pzem = df_pzem.sort_values('timestamp_dt')

# Proses Data Log (Centang Web)
df_logs = pd.DataFrame.from_dict(raw_logs, orient='index')
df_logs['timestamp_dt'] = pd.to_datetime(df_logs['timestamp'], unit='ms')
df_logs = df_logs.sort_values('timestamp_dt')

# Jahit Daya & Log
df_final = pd.merge_asof(df_pzem, df_logs, on='timestamp_dt', direction='backward')

# Ambil Cuaca Satelit (Open-Meteo)
start_date = df_final['timestamp_dt'].min().strftime('%Y-%m-%d')
end_date = df_final['timestamp_dt'].max().strftime('%Y-%m-%d')
lat, lon = -7.4245, 109.2302 # Purwokerto/Banjarnegara
url_weather = f"https://archive-api.open-meteo.com/v1/archive?latitude={lat}&longitude={lon}&start_date={start_date}&end_date={end_date}&hourly=temperature_2m&timezone=Asia%2FJakarta"

try:
    res = requests.get(url_weather)
    weather_data = res.json()
    df_weather = pd.DataFrame({
        'timestamp_dt': pd.to_datetime(weather_data['hourly']['time']),
        'Suhu_Outdoor': weather_data['hourly']['temperature_2m']
    }).sort_values('timestamp_dt')
    df_train_full = pd.merge_asof(df_final, df_weather, on='timestamp_dt', direction='nearest')
except:
    df_train_full = df_final.copy()
    df_train_full['Suhu_Outdoor'] = 28.0

# Bersihkan Dataset
kolom_penting = ['timestamp_dt', 'Daya', 'Suhu', 'Suhu_Outdoor', 'AC', 'HP', 'Laptop', 'Magicom', 'TV', 'Waterheater']
df_train = df_train_full[[k for k in kolom_penting if k in df_train_full.columns]].copy()
df_train.fillna({'AC': False, 'HP': False, 'Laptop': False, 'Magicom': False, 'TV': False, 'Waterheater': False, 'Daya': 0, 'Suhu': 27.0, 'Suhu_Outdoor': 28.0}, inplace=True)
df_train['Daya'] = pd.to_numeric(df_train['Daya'])
df_train['Suhu_Indoor'] = pd.to_numeric(df_train['Suhu'])
df_model = df_train[['timestamp_dt', 'Daya', 'Suhu_Indoor', 'Suhu_Outdoor', 'AC', 'HP', 'Laptop', 'Magicom', 'TV', 'Waterheater']].tail(1000).reset_index(drop=True)

print("✅ [Step 2] Dataset Super Siap (1000 baris terakhir).")

print("⏳ [Step 3] AI sedang mempelajari pola daya (SARIMAX)...")
y = df_model['Daya']
X = df_model[['Suhu_Indoor', 'Suhu_Outdoor', 'AC', 'HP', 'Laptop', 'Magicom', 'TV', 'Waterheater']].astype(float)

model_sarimax = SARIMAX(y, exog=X, order=(1, 0, 1))
hasil_sarimax = model_sarimax.fit(disp=False)
print("✅ [Step 3] Model SARIMAX selesai dilatih.")

BATAS_DAYA = 900.0

class SmartHomeEnv(gym.Env):
    def __init__(self, dataset, sarimax_model):
        super(SmartHomeEnv, self).__init__()
        self.data = dataset.copy()
        self.model_sarimax = sarimax_model
        self.current_step = 0
        self.action_space = spaces.Discrete(4) # 0:Stable, 1:AC off, 2:Magicom off, 3:Heater off
        self.observation_space = spaces.Box(low=0, high=2000, shape=(6,), dtype=np.float32)

    def reset(self):
        self.current_step = 0
        return self._get_obs()

    def _get_obs(self):
        row = self.data.iloc[self.current_step]
        return np.array([row['Daya'], row['Suhu_Indoor'], row['Suhu_Outdoor'], row['AC'], row['Magicom'], row['Waterheater']], dtype=np.float32)

    def step(self, action):
        row = self.data.iloc[self.current_step]
        prediksi_daya = row['Daya']
        if action == 1 and row['AC'] == 1: prediksi_daya -= 350
        if action == 2 and row['Magicom'] == 1: prediksi_daya -= 300
        if action == 3 and row['Waterheater'] == 1: prediksi_daya -= 250

        reward = -100 if prediksi_daya > BATAS_DAYA else 10
        if action != 0 and row['Daya'] < 600: reward -= 5

        self.current_step += 1
        done = self.current_step >= len(self.data) - 1
        return self._get_obs(), reward, done, {}

env = SmartHomeEnv(df_model, hasil_sarimax)
print("✅ [Step 4] Arena Simulasi RL dibuat.")

print("⏳ [Step 5] Agen RL berlatih 10.000 skenario (PPO)...")
agen_rl = PPO("MlpPolicy", env, verbose=0, learning_rate=0.0005)
agen_rl.learn(total_timesteps=10000)
print(" [Step 5] Agen RL menjadi pintar!")

# ==========================================
# STEP 6: MENYIMPAN OTAK KE GOOGLE DRIVE
# ==========================================
print(" [Step 6] Mengamankan model ke Google Drive...")
FOLDER_SIMPAN = '/content/drive/MyDrive/SKRIPSHIT/'

# Simpan RL Model (Format .zip otomatis)
agen_rl.save(f"{FOLDER_SIMPAN}model_rl_kairo")

# Simpan SARIMAX (Format .pkl)
with open(f"{FOLDER_SIMPAN}model_sarimax_kairo.pkl", 'wb') as f:
    pickle.dump(hasil_sarimax, f)

print("Selesai! Model berhasil diamankan.")