
name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  python-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile check
        run: |
          python -m py_compile pekerja_ai.py rekap_harian.py sarimax_utils.py sarimax_firebase_train.py rl_retrain_budget.py model_ai/pekerja_ai.py
          
      - name: Download Model AI dari Google Drive
        run: |
          mkdir -p model_ai
          python -m pip install gdown
          gdown --id "1XLPfnCjT5EGf-zj3p_6q3XYDBJaCPgVy" -O "model_ai/model_sarimax_kairo (1).pkl"
          gdown --id "1Q5G4sOR4wi-5OWqes2zwU4AvMni8meMY" -O "model_ai/model_rl_kairo (1).zip"
          echo " === HASIL DOWNLOAD ==="
          ls -la model_ai/
