name: Robot-Rekap-Kairo-dan-AI

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  job-rekap-dan-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Library
        run: |
          pip install firebase-admin pytz
          pip install -r requirements.txt

      - name: Download Model AI dari Google Drive
        run: |
          mkdir -p model_ai
          python -m pip install gdown
          gdown --id "1H9tTCCeQVyWB3u2NXOYtRf_X1SZUJu5" -O "model_ai/model_sarimax_kairo (1).pkl"
          gdown --id "1Q5G4sOR4wi-5OWqes2zwU4AvMni8meMY" -O "model_ai/model_rl_kairo (1).zip"

      - name: Run Script Rekap Harian
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }} # Ini jembatan kuncinya!
        run: python rekap_harian.py

      - name: Jalankan Mandor AI
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }} # Ini juga jembatan kuncinya!
        run: python pekerja_ai.py
